<?php
namespace Camspiers\StatisticalClassifier\Tokenizer;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:06:10.
 */
class WordTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Word
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Word;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Tokenizer\Word::tokenize
     * @todo   Implement testTokenize().
     */
    public function testTokenize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
