#!/usr/bin/env bash
cd statistical-classifier
git fetch --all
git reset --hard origin/master
composer install --dev
phpdoc -d src/ -t ../docs/ --title="PHP Classifier" --defaultpackagename="Statistical Classifier"
cd ..
statistical-classifier/bin/compile
VERSION=$(php classifier.phar --version)
echo ${VERSION/PHP Classifier version } > classifier.phar.version