<?php
namespace Camspiers\StatisticalClassifier\Console\Command\Server;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-13 at 17:34:16.
 */
class RunCommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StartCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RunCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Console\Command\Server\StartCommand::serve
     * @todo   Implement testServe().
     */
    public function testServe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
