<?php

namespace Camspiers\StatisticalClassifier\DataSource;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:06:09.
 */
class ConverterTest extends \PHPUnit_Framework_TestCase
{
    public function testRun()
    {
        $data = array(
            array(
                'document' => 'Test',
                'category' => 'Test'
            )
        );

        $convertTo = $this->getMock(
            __NAMESPACE__ . '\\DataSourceInterface'
        );

        $convertTo->expects($this->once())
            ->method('setData')
            ->with($this->equalTo($data));

        $convertTo->expects($this->once())
            ->method('write');

        $converter = new Converter(
            new DataArray(
                $data
            ),
            $convertTo
        );

        $converter->run();
    }
}
