<?php
namespace Camspiers\StatisticalClassifier\Index;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:06:10.
 */
class CachedIndexTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CachedIndex
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CachedIndex;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Index\CachedIndex::setPrepared
     * @todo   Implement testSetPrepared().
     */
    public function testSetPrepared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Index\CachedIndex::preserve
     * @todo   Implement testPreserve().
     */
    public function testPreserve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
