<?php
namespace Camspiers\StatisticalClassifier\ClassificationRule;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:06:07.
 */
class NaiveBayesTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var NaiveBayes
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new NaiveBayes;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Camspiers\StatisticalClassifier\ClassificationRule\NaiveBayes::classify
     * @todo   Implement testClassify().
     */
    public function testClassify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
