<?php
namespace Camspiers\StatisticalClassifier\Classifier;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-26 at 18:06:08.
 */
class GenericClassifierTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenericClassifier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new GenericClassifier;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::is
     * @todo   Implement testIs().
     */
    public function testIs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::setTransforms
     * @todo   Implement testSetTransforms().
     */
    public function testSetTransforms()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::addTransform
     * @todo   Implement testAddTransform().
     */
    public function testAddTransform()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::prepareIndex
     * @todo   Implement testPrepareIndex().
     */
    public function testPrepareIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::setIndex
     * @todo   Implement testSetIndex().
     */
    public function testSetIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Camspiers\StatisticalClassifier\Classifier\GenericClassifier::classify
     * @todo   Implement testClassify().
     */
    public function testClassify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
