<?php
namespace Camspiers\StatisticalClassifier\Classifier;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-13 at 17:34:15.
 */
class SVMTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SVM
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    public function testClassify()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
