<?php
namespace Camspiers\StatisticalClassifier\Console\Command\Train;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-04-13 at 17:34:17.
 */
class PDOCommandTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PDOCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PDOCommand;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testExecute()
    {
        $this->markTestIncomplete();
    }
}
